name: JoinQuitMessages
version: '${project.version}'
main: org.info_0.joinquitmessages.JoinQuitMessages
api-version: '1.20'
folia-supported: true
commands:
  jqm:
    description: "Toggle join messages"
    usage: "/jqm toggle"
    aliases:
      - join-quit
permissions:
  jqm.prevent-messages:
    default: false
    description: "Prevent jqm messages."